const STORAGE_KEY = 'socialCommentCleanerSettings';
const form = document.getElementById('settingsForm');
const status = document.getElementById('status');
const input = (id) => document.getElementById(id);
const value = (id) => input(id).value;
function collect() { return { platform: 'instagram', targetPostUrl: value('targetPostUrl'), whitelist: value('whitelist'), deleteKeywords: value('deleteKeywords'), sessionLimit: value('sessionLimit'), sessionMaxMinutes: value('sessionMaxMinutes'), pagination: { enabled: input('autoLoadEnabled').checked, maxBatches: value('maxAutoLoadBatches'), noGrowthAttempts: value('noGrowthAttempts'), stableWaitMs: value('batchStableWaitMs'), allowDeletion: input('allowDeletionAutoLoad').checked }, pace: { operation: { distribution: 'log-normal', meanSeconds: value('operationMean'), minSeconds: value('operationMin'), maxSeconds: value('operationMax') }, rest: { distribution: 'log-normal', meanSeconds: value('restMean'), minSeconds: value('restMin'), maxSeconds: value('restMax') }, deleteDialogDelay: { distribution: 'log-normal', meanSeconds: value('deleteDialogMean'), minSeconds: value('deleteDialogMin'), maxSeconds: value('deleteDialogMax') }, maxConsecutive: value('maxConsecutive'), rateLimit: { perMinute: value('perMinute'), perHour: value('perHour') } } }; }
function render(settings) { const pace = settings.pace; if (settings.sessionLimit !== 'unlimited' && ![...input('sessionLimit').options].some((option) => option.value === String(settings.sessionLimit))) { input('sessionLimit').append(new Option(`${settings.sessionLimit} 条`, settings.sessionLimit)); } const fields = { targetPostUrl: settings.targetPostUrl, whitelist: settings.whitelist, deleteKeywords: settings.deleteKeywords, sessionLimit: settings.sessionLimit, sessionMaxMinutes: settings.sessionMaxMinutes, maxAutoLoadBatches: settings.pagination.maxBatches, noGrowthAttempts: settings.pagination.noGrowthAttempts, batchStableWaitMs: settings.pagination.stableWaitMs, operationMean: pace.operation.meanSeconds, operationMin: pace.operation.minSeconds, operationMax: pace.operation.maxSeconds, restMean: pace.rest.meanSeconds, restMin: pace.rest.minSeconds, restMax: pace.rest.maxSeconds, deleteDialogMean: pace.deleteDialogDelay.meanSeconds, deleteDialogMin: pace.deleteDialogDelay.minSeconds, deleteDialogMax: pace.deleteDialogDelay.maxSeconds, maxConsecutive: pace.maxConsecutive, perMinute: pace.rateLimit.perMinute, perHour: pace.rateLimit.perHour }; Object.entries(fields).forEach(([id, fieldValue]) => { input(id).value = fieldValue; }); input('autoLoadEnabled').checked = settings.pagination.enabled; input('allowDeletionAutoLoad').checked = settings.pagination.allowDeletion; updateSummary(); }
function updateSummary() { document.getElementById('advancedSummary').textContent = `当前：每分钟 ${value('perMinute')} 次、每小时 ${value('perHour')} 次`; }
function validate(requireTarget) { const settings = InstagramCommentPaceConfig.validateSettings(collect()); const target = InstagramCommentRules.normalizeTargetUrl(settings.targetPostUrl); if (requireTarget && !target) { input('targetPostUrl').setAttribute('aria-invalid', 'true'); throw new Error('请输入 Instagram 帖子或 Reels 的完整 URL。'); } input('targetPostUrl').removeAttribute('aria-invalid'); return { ...settings, targetPostUrl: target || settings.targetPostUrl }; }
async function save(requireTarget = false) { const settings = validate(requireTarget); await chrome.storage.sync.set({ [STORAGE_KEY]: settings }); updateSummary(); return settings; }
let saveTimer;
function scheduleSave() { clearTimeout(saveTimer); saveTimer = setTimeout(() => save(false).catch((error) => { status.textContent = error.message || '自动保存失败'; }), 350); }
async function launch(mode) { try { status.textContent = '准备开始...'; const settings = await save(true); const response = await chrome.runtime.sendMessage({ type: 'ICC_LAUNCH', targetUrl: settings.targetPostUrl, mode }); if (!response?.ok) throw new Error(response?.reason || '启动失败'); status.textContent = mode === 'preview' ? '预览已开始' : '已开始'; } catch (error) { status.textContent = error.message || '启动失败'; } }
// 暂停和停止只控制已经打开的目标帖子，不会重新导航或启动新任务。
async function control(action) { try { const settings = await save(true); const response = await chrome.runtime.sendMessage({ type: action === 'pause' ? 'ICC_PAUSE' : 'ICC_STOP', targetUrl: settings.targetPostUrl }); if (!response?.ok) throw new Error(response?.reason || `${action === 'pause' ? '暂停' : '停止'}失败`); status.textContent = action === 'pause' ? '已暂停' : '已停止'; } catch (error) { status.textContent = error.message || `${action === 'pause' ? '暂停' : '停止'}失败`; } }
document.addEventListener('DOMContentLoaded', async () => { const stored = (await chrome.storage.sync.get(STORAGE_KEY))[STORAGE_KEY]; render(InstagramCommentPaceConfig.normalizeSettings(stored)); form.querySelectorAll('input,textarea,select').forEach((node) => node.addEventListener('input', scheduleSave)); });
form.addEventListener('submit', (event) => { event.preventDefault(); launch('run'); });
input('previewButton').addEventListener('click', () => launch('preview'));
input('pauseButton').addEventListener('click', () => control('pause'));
input('stopButton').addEventListener('click', () => control('stop'));
