const STORAGE_KEY = 'socialCommentCleanerSettings';
const form = document.getElementById('settingsForm');
const status = document.getElementById('status');
const input = (id) => document.getElementById(id);
const value = (id) => input(id).value;
let activePlatformId = '';
function collect() { return { platform: activePlatformId, platformId: activePlatformId, targetPostUrl: value('targetPostUrl'), targetUrl: value('targetPostUrl'), whitelist: value('whitelist'), deleteKeywords: value('deleteKeywords'), sessionLimit: value('sessionLimit'), sessionMaxMinutes: value('sessionMaxMinutes'), pace: { operation: { distribution: 'log-normal', meanSeconds: value('operationMean'), minSeconds: value('operationMin'), maxSeconds: value('operationMax') }, rest: { distribution: 'log-normal', meanSeconds: value('restMean'), minSeconds: value('restMin'), maxSeconds: value('restMax') }, deleteDialogDelay: { distribution: 'log-normal', meanSeconds: value('deleteDialogMean'), minSeconds: value('deleteDialogMin'), maxSeconds: value('deleteDialogMax') }, refreshRest: { distribution: 'log-normal', meanSeconds: Number(value('refreshMean')) * 60, minSeconds: Number(value('refreshMin')) * 60, maxSeconds: Number(value('refreshMax')) * 60 }, maxConsecutive: value('maxConsecutive'), rateLimit: { perMinute: value('perMinute'), perHour: value('perHour') } } }; }
function applyPlatform(settings) { activePlatformId = settings.platformId; SocialCommentPlatformForm.renderPlatformOptions(input('platformId'), activePlatformId); SocialCommentPlatformForm.applyMetadata(input('targetPostUrl'), settings); }
function render(rawSettings) { const settings = SocialCommentPlatformForm.normalize(SocialCommentPaceConfig.normalizeSettings(rawSettings)); applyPlatform(settings); const pace = settings.pace; if (settings.sessionLimit !== 'unlimited' && ![...input('sessionLimit').options].some((option) => option.value === String(settings.sessionLimit))) { input('sessionLimit').append(new Option(`${settings.sessionLimit} 条`, settings.sessionLimit)); } const fields = { targetPostUrl: settings.targetUrl || settings.targetPostUrl, whitelist: settings.whitelist, deleteKeywords: settings.deleteKeywords, sessionLimit: settings.sessionLimit, sessionMaxMinutes: settings.sessionMaxMinutes, operationMean: pace.operation.meanSeconds, operationMin: pace.operation.minSeconds, operationMax: pace.operation.maxSeconds, restMean: pace.rest.meanSeconds, restMin: pace.rest.minSeconds, restMax: pace.rest.maxSeconds, deleteDialogMean: pace.deleteDialogDelay.meanSeconds, deleteDialogMin: pace.deleteDialogDelay.minSeconds, deleteDialogMax: pace.deleteDialogDelay.maxSeconds, refreshMean: Math.round(pace.refreshRest.meanSeconds / 60), refreshMin: Math.round(pace.refreshRest.minSeconds / 60), refreshMax: Math.round(pace.refreshRest.maxSeconds / 60), maxConsecutive: pace.maxConsecutive, perMinute: pace.rateLimit.perMinute, perHour: pace.rateLimit.perHour }; Object.entries(fields).forEach(([id, fieldValue]) => { input(id).value = fieldValue; }); updateSummary(); }
function updateSummary() { document.getElementById('advancedSummary').textContent = `当前：每分钟 ${value('perMinute')} 次、每小时 ${value('perHour')} 次`; }
function validate(requireTarget) { const paced = SocialCommentPaceConfig.validateSettings(collect()); const settings = SocialCommentPlatformForm.normalize(paced, { preferPlatformId: true }); activePlatformId = settings.platformId; const platform = SocialCommentPlatformRegistry.get(settings.platformId); const target = platform?.identity?.normalizeTargetUrl?.(settings.targetUrl) || ''; if (requireTarget && !target) { input('targetPostUrl').setAttribute('aria-invalid', 'true'); throw new Error(`请输入 ${platform?.displayName || '当前平台'} 目标页面的完整 URL。`); } input('targetPostUrl').removeAttribute('aria-invalid'); return { ...settings, targetUrl: target || settings.targetUrl, targetPostUrl: target || settings.targetUrl }; }
async function save(requireTarget = false) { const settings = validate(requireTarget); await chrome.storage.sync.set({ [STORAGE_KEY]: settings }); updateSummary(); return settings; }
let saveTimer;
function scheduleSave() { clearTimeout(saveTimer); saveTimer = setTimeout(() => save(false).catch((error) => { status.textContent = error.message || '自动保存失败'; }), 350); }
async function launch(mode) { try { status.textContent = '准备开始...'; const settings = await save(true); const response = await chrome.runtime.sendMessage({ type: 'SC_LAUNCH', platformId: settings.platformId, canonicalTargetUrl: settings.targetUrl, targetUrl: settings.targetUrl, mode }); if (!response?.ok) throw new Error(response?.reason || '启动失败'); status.textContent = mode === 'preview' ? '预览已开始' : '已开始'; } catch (error) { status.textContent = error.message || '启动失败'; } }
// 暂停和停止只控制已经打开的目标帖子，不会重新导航或启动新任务。
async function control(action) { try { const settings = await save(true); const response = await chrome.runtime.sendMessage({ type: action === 'pause' ? 'SC_PAUSE' : 'SC_STOP', platformId: settings.platformId, canonicalTargetUrl: settings.targetUrl, targetUrl: settings.targetUrl }); if (!response?.ok) throw new Error(response?.reason || `${action === 'pause' ? '暂停' : '停止'}失败`); status.textContent = action === 'pause' ? '已暂停' : '已停止'; } catch (error) { status.textContent = error.message || `${action === 'pause' ? '暂停' : '停止'}失败`; } }
document.addEventListener('DOMContentLoaded', async () => { const stored = (await chrome.storage.sync.get(STORAGE_KEY))[STORAGE_KEY]; render(stored); form.querySelectorAll('input,textarea,select').forEach((node) => node.addEventListener('input', scheduleSave)); input('platformId').addEventListener('change', () => { activePlatformId = value('platformId'); const targetInput = input('targetPostUrl'); const currentTarget = targetInput.value.trim(); const platform = SocialCommentPlatformRegistry.get(activePlatformId); const canonicalTarget = platform?.identity?.normalizeTargetUrl?.(currentTarget) || ''; if (currentTarget && !canonicalTarget) targetInput.value = ''; else if (canonicalTarget) targetInput.value = canonicalTarget; const settings = SocialCommentPlatformForm.normalize(collect(), { preferPlatformId: true }); applyPlatform(settings); targetInput.removeAttribute('aria-invalid'); scheduleSave(); }); });
form.addEventListener('submit', (event) => { event.preventDefault(); launch('run'); });
input('previewButton').addEventListener('click', () => launch('preview'));
input('pauseButton').addEventListener('click', () => control('pause'));
input('stopButton').addEventListener('click', () => control('stop'));
